name: master-pr

on:
    workflow_dispatch:
    push:
        branches: ["develop"]

jobs:
    sync:
        runs-on: ubuntu-latest
        permissions:
            pull-requests: write
        steps:
            - name: create-pr-on-master
              run: gh pr create --fill --base master
              env:
                GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                