name: master-pr

on:
    workflow_dispatch:
    push:
        branches: ["develop"]

jobs:
    sync:
        runs-on: ubuntu-latest
        permissions:
            pull-requests: write
        steps:
            - uses: actions/checkout@v4
            - name: create-pr-on-master
              run: gh pr create --title="auto-merge" --body="auto PR to sync develop and master branches" --base origin/master
              env:
                GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
