name: master-pr

on:
    workflow_dispatch:
    push:
        branches: ["develop"]

jobs:
    sync:
        permissions:
            pull-requests: write
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: create-pr-on-master
              run: gh pr create --fill-first --base=master --head=develop
              env:
                GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
