name: Rust

on:
  workflow_dispatch:
  push:
  merge_group:
    types: [checks_requested]
  pull_request:
    branches: [ "develop" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Cache
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    - name: Output rust version for educational purposes
      run: rustup --version
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
